### ISSUE TITLE
Sync API

### ISSUE THREAD

**Issue by vasco-santos** [hacdias/human-to-milliseconds#2]
Hey @hacdias 

In `js-ipfs`, I am using this module for converting human time to milliseconds and I asked myself why you provide an API with either callbacks or promises. As we are not doing any async job, it could simply return the value in milliseconds. 

For context, in the case of my PR [ipfs/js-ipfs#2184](https://github.com/ipfs/js-ipfs/pull/2184), thanks to this module I need to have an async function to start, instead of doing everything inside a constructor, as it cannot be async.

As you do not update this module for more than a year, if you are willing to change this, you could release a breaking change modifying the API to just return the values. Let me know what you think

**Comment by hacdias** [comment]
Hey @vasco-santos! Sorry for taking so long replying to this. I have absolutely no clue why I decided to make this async and it doesn't seem to have been a good decision nor to make any sense.

I'm gonna release 2.0.0 with a sync-only API.

**Comment by hacdias** [comment]
Done!

**Comment by vasco-santos** [comment]
Thanks @hacdias ❤️
